name: Generate .env
description: Generate a .env file from variables and secrets
author: Kiruse
inputs:
  env:
    description: Contents of the .env file
  clone:
    description: List of variables to clone from the environment
  require:
    description: List of required variables. These must not be empty (after trim). Items separated by commas & newlines.
runs:
  using: node20
  main: dist/index.js
