name: Generate .env
description: Generate a .env file from variables and secrets
author: Kiruse
inputs:
  env:
    description: Contents of the .env file
    required: true
runs:
  using: composite
  steps:
  - run: echo "${{ inputs.env }}" >> .env
    shell: bash
